name: Build Test Deb Package

on:
  pull_request:
    branches:
      - main
jobs:
  build-test-deb-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Debian Package in Docker
        run: |
          docker run --rm -v $(pwd):/tmp debian:bullseye-slim bash -c \
          "cd /tmp \
          && chmod 555 homeassistant-supervised/DEBIAN/p* \
          && dpkg-deb --build --root-owner-group homeassistant-supervised"
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: homeassistant-supervised.deb
          path: homeassistant-supervised.deb