name: Build Test Deb Package

on:
  pull_request:
    branches:
      - main
jobs:
  build-test-deb-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: chmod 555 homeassistant-supervised/DEBIAN/p*
      - run: dpkg-deb --build --root-owner-group homeassistant-supervised
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: homeassistant-supervised.deb
          path: homeassistant-supervised.deb